fix session_id and session_age inputs
maxmind/minfraud-api-perl pull request #30
Opened 2017-06-28 02:18 UTC by oalders

2017-06-28 20:13 UTC, oschwald requested changes

2017-06-28 20:13 UTC, oschwald commented on lib/WebService/MinFraud/Record/Device.pm
> -    isa       => SessionID,
We can probably remove this type since we are no longer using it.

2017-06-28 20:13 UTC, oschwald commented on lib/WebService/MinFraud/Validator.pm
> +                    },
I don't see any tests for the validation and we only seem to use the `full-request.json` in an author test.

2017-06-28 21:23 UTC, oalders commented on lib/WebService/MinFraud/Record/Device.pm
> -    isa       => SessionID,
Fixed in a9c5a007

2017-06-28 21:23 UTC, oalders commented on lib/WebService/MinFraud/Validator.pm
> +                    },
Fixed in d880637db

2017-06-29 14:23 UTC, oschwald commented on lib/WebService/MinFraud/Validator.pm
> +                    session_age     => '//num',
Any reason not to set the minimum to 0? I think the syntax is something line `range => {min => 0}`.

2017-07-05 14:46 UTC, merged